spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/your_db_name
    username: your_username
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info

# Configuration des logs
logging:
  level:
    org.springframework: DEBUG  # Niveau de log pour Spring Framework
    org.hibernate: DEBUG         # Niveau de log pour Hibernate
    root: INFO                   # Niveau de log global
  file:
    name: logs/application.log   # Le fichier où les logs seront sauvegardés
